### ISSUE TITLE
Cannot reselect other account types when creating transactions

### ISSUE THREAD

**Issue by corinetiah** [maffin-io/maffin-app#832]
If you accidentally select a wrong account while entering transactions, Maffin doesn't let you reselect a new account, even after you close the transaction window and click [Add] again. 
<img width="485" alt="Screenshot 2024-04-07 at 10 57 18 PM" src="https://github.com/maffin-io/maffin-app/assets/124553339/89c2c211-657f-4024-9cca-89ae4253f9d0">

**Comment by argaen** [comment]
Yeah this is a recent bug I added in PR #809.

The culprit is https://github.com/maffin-io/maffin-app/pull/809/files#diff-28a1eddf39fdf2988e181547dae13df9391fab5a9623fa0df533fc11ef8ea214R86. The problem is that once you select an account type, it only allows you to select valid sub account types for the selected one. 

This was initially added so you can pass default account types when adding a new transaction (i.e. so the user sees select ASSET account) for some specific actions. I think instead of using getValue('account') probably need to forward defaultValues and use that instead
