### ISSUE TITLE
Demo and free versions are now showing incorrect investment type

### ISSUE THREAD

**Issue by corinetiah** [maffin-io/maffin-app#843]
Demo and free versions are showing investment parent account as ASSET type instead of INVESTMENT.

**Comment by argaen** [comment]
Yeah this... I need to document it. The way parent non parent works for investments is the following:

A parent can only be an INVESTMENT type if all their children are NON PARENT investments. The reason is because if you start mixing parents and non parents for an investment parent, the weights charts and others will show weird stuff or will directly not work.

I guess the solution would be to pick all the non parent investments within and then show those but.. haven't implemented yet. I'll have a look at some point. Leaving this open as a reminder for this
